### ISSUE TITLE
CI를 통해 PR 시 기본적으로 테스트를 수행한다.

### ISSUE THREAD

**Issue by Nine-JH** [fcstudy-project/FastTime#13]
# 목적
## 1. 테스트 누락
* 오늘(8/22) 일자로 다른분에게 테스트 관련 실패를 공지 받았습니다. 아마도 PR을 하기 전 테스트를 하지 않은게 화근이었습니다.
* 휴먼 에러로 테스트에 대한 불안정성을 계속 가져가는 것 보다는, `CI` 를 사용해 계속해서 Testing을 수행하는 것이 바람직하다 생각을 하게 되어 제안을 드립니다. 
<br>
<br>

## 2. 그럼 어떻게 CI를 구현할 것인가?
방법은 여러가지가 있습니다.
* AWS PipeLine Series
* Jenkins
* Github Action
* etc

저는 이 중 `Github Action`을 사용하려고 생각중입니다. 이유는 다음과 같은데요
* 개별적인 서버가 필요 없음.
  * AWS, Jenkins 의 경우 따로 서버가 필요합니다. 하지만, Github Action의 경우에는 Github 측에서 해결해줍니다.
  * 위의 이유로 추가적인 관리포인트가 늘어나지 않아 개발에 유리할것으로 보입니다.
* 가장 Github PR에 최적화되어있음.
  * 물론 Jenkins의 확장성에는 비할바가 못되지만, 현재 사용중인 Github에서만큼은 높은 지원율이 보이기 때문에 사용할 만 할 것 같습니다.  
<br>
<br>

여러분들의 의견이 궁금하네요

# 개발내용
- [ ] CI 스크립트를 작성한다. 
- [ ] 테스트를 수행해본다.

<br>
<br>

**Comment by JeongUijeong** [comment]
좋은 생각 같습니다! CI 를 통해 PR전에 빌드와 테스트까지 자동 수행하면 더 안정적인 개발이 가능하겠네요! 툴로 Github Action 사용하는 것도 찬성입니다. 😀

**Comment by ghrltjdtprbs** [comment]
동의합니다. 좀 더 안정적인 개발을 위해서는 추가하는 것이 좋을 것 같네요! 
언급하셨던 테스트 관련  실패는 정확히 어떤 부분인지 알려주실 수 있나요?

**Comment by Nine-JH** [comment]
> 동의합니다. 좀 더 안정적인 개발을 위해서는 추가하는 것이 좋을 것 같네요!
> 언급하셨던 테스트 관련 실패는 정확히 어떤 부분인지 알려주실 수 있나요?

Post 의 필드 `anonymity` 의 오타가 있어 수정을 실시했는데 테스트코드에는 실제로 반영이 되지 않아 발생한 문제였습니다.
PostMan과 같은 API 테스트툴로 로컬 환경에서는 테스트를 진행했지만 정작 테스트코드는 실행하지 않아 그대로 문제가 발생한 상황이었습니다!
