### ISSUE TITLE
ResponseEntity를 Custom한다. 

### ISSUE THREAD

**Issue by JeongUijeong** [fcstudy-project/FastTime#14]
# 🎯목적
## 1. 응답 형태의 일관성
HttpStatus 와 각 요청에 대한 특수한 객체를 응답하는 것이 아닌 code, message, data를 응답하여 좀 더 일관성 있는 응답을 할 수 있게 됩니다. 

`code`: 상태 코드를 담아 보냅니다. (ex. 200, 201, 401 등)
`message`: 상태에 대한 메시지를 담아 보냅니다. 예외 처리의 경우 에러 메시지를 보낼 수 있습니다. 
`data`: 요청한 데이터를 보냅니다. 객체를 담아 보낼 수 있습니다. 

적용할 경우 아래와 같은 응답 형태를 가집니다.  
```json
{
    "code": 200,
    "message": "Success :)"
    "data": {
        
    }
}
```

## 2. 상세하고 명시적인 응답
기존에 사용하고 있던 HttpStatus에서 제공하는 상태코드 외에 좀 더 상세한 저희 서비스에 대한 맞춤 상태코드를 지정할 수 있습니다. 
HttpStatus를 사용해도 되지만, 서비스에 대해 더 많은 정보를 내포하는 코드를 응답할 수 있다는 것이 장점이라고 생각해 제안드립니다. 

예시를 통해 설명 드리겠습니다. 
400101라는 6 자리 상태 코드를 응답했다면, 
```
400: 잘못된 요청(Http Status)
10: Argument Not Valid
1: 게시글에서
```
이처럼, 세 자리 숫자로 응답하는 HttpStatus 보다 상세한 서비스 상태를 응답할 수 있게 됩니다. 
BadRequest 상태 코드로 통일해야 했던 때보다 Argument 검증 실패, 유효하지 않은 요청, 권한 부족 등 여러 상황에 맞는 코드를 커스텀 하여 사용할 수 있습니다. 

흔히 사용되는 HttpStatus 코드보다 복잡하고 다양한 상태 코드를 가질 수 있고, 변경 소지가 있기 때문에, 개발자가 상태 코드 문서를 확인하지 않아도 되도록, message에 상태 코드의 의미를 적어 message를 보고 상태 코드를 이해할 수 있게 합니다. 

---
# ✔️요약
- ResponseEntity를 Custom 하여, 일관된 형태의 응답을 가능케 한다. 
- 상태 코드도 저희 서비스에 맞게 Custom 하여, 보다 상세하고 명시적인 소통을 도모한다. 
- 두 가지 제안을 드렸는데, 여러분들의 의견은 어떠신가요?

---
# 🎀결론
- 23.08.22 회의 결과, Response Entity를 커스텀 하되, 상태 코드는 HttpStatus를 그대로 쓰기로 한다. 
- 명시적이고 상세한 소통을 위해 message를 잘 작성하기로 한다. 

## 요구되는 개발 내용
- [ ] ResponseDTO Class를 생성한다. 
- [ ] RestController에 ResponseDTO를 적용한다.

**Comment by KwonJuHwan** [comment]
'더 많은 정보를 내포하는 코드를 응답할 수 있다는 것이 장점'이 마음에 드네요. 저는 좋습니다😃

**Comment by Nine-JH** [comment]
너무 좋은 제안이네요!

**Comment by ghrltjdtprbs** [comment]
## 🫠

**Comment by JeongUijeong** [comment]
커스텀 StatusCode 규칙을 만들어서 거기에 맞게 각자 6자리 정수를 입력하도록 하는 게 좋을까요?
enum으로 작성을 해볼까 했는데, 쉽지 않네요.. 회의 때 다시 말씀 드리도록 하겠습니다 😭
