### ISSUE TITLE
각 도메인의 엔터티와 레포지토리에 대한 접근은 최대한 해당 도메인 서비스에서 이뤄지도록 한다

### ISSUE THREAD

**Issue by JeongUijeong** [fcstudy-project/FastTime#26]
# 🎯목적
## 한 레포지토리에 대해 여러 서비스 혹은 컨트롤러가 접근하지 않도록 제한한다. 

각 도메인의 엔터티와 레포지토리에 대한 접근은 최대한 해당 도메인 서비스에서 이뤄지도록 한다. 

지난 멘토링 시간에 다른 도메인의 엔터티나 레포지토리를 사용하기 보다 해당 도메인의 서비스를 호출하여 서비스 내 구현된 메서드를 이용해 기능을 구현하는 것이 바람직하다는 조언을 들을 수 있었습니다. 

저도 다른 도메인 레포지토리에 직접 접근하는 것보다, 해당 도메인 서비스만 스스로의 레포지토리에 접근하도록 하는 것이 더 바람직하다고 생각합니다. 

이를 위해 아래와 같은 몇 가지 기능을 요청 드리고 싶습니다. 

---

# 🎀요청
- 회원
  - 회원 ID로 회원을 조회할 수 있는 기능 (ex. getMember(Long id))
- 게시글
  - 게시글 ID로 게시글을 조회할 수 있는 기능 (ex. getPost(Long id))
  - 게시글 신고 상태 변경 기능 (서비스 내에 구현 부탁드립니다!)
  - 게시글 삭제 기능 (서비스 내에 구현 부탁드립니다!)
 
저도 댓글 조회 기능을 추가적으로 구현하도록 하겠습니다!

---

# ⌨️개발 내용
- [x] getComment(Long id)
- [x] getCommentsByPost(Post post)
- [x] getCommentsByMember(Member member)

---
혹시 다른 이견이 있으신 분들은 코멘트 남겨주세요!👀

**Comment by ghrltjdtprbs** [comment]
정확히 어떤 기능을 구현하기 위해 저 기능이 필요하신가요??

**Comment by Nine-JH** [comment]
음 이러면 interface를 사용해 usecase pattern 형식으로 사용해보는 것도 나쁘지 않겠네요.
사실 이게 tdd에 더 잘 어울리긴 하죠 😀
