### ISSUE TITLE
예외 처리를 리팩토링한다.

### ISSUE THREAD

**Issue by Nine-JH** [fcstudy-project/FastTime#30]
# 목적
## 1. 의도치 않은 ExceptionAdvice 처리 
advice의 범위를 정확히 정하지 않아 이에 대한 문제가 발생하는 경우가 있습니다. 결국 이는 ControllerTest에 영향이 가겠죠

#### 정상 Flow
![image](https://github.com/fcstudy-project/FastTime/assets/139187207/16947647-7d76-4d16-af56-a2f186d745a3)

#### 비정상 Flow
![image](https://github.com/fcstudy-project/FastTime/assets/139187207/843e0e33-2eb2-460b-ab28-2e5e078b52fa)

<br>
<br>

## 2. 중복되는 처리
가장 대표적인예시로 `BindException`이 있습니다. 모든 `ControllerAdvice`에서 처리하다보니 중복되는 현상이 발견되고 있습니다. 이는 결국 첫번째 문제점을 야기하게 됩니다.
![image](https://github.com/fcstudy-project/FastTime/assets/139187207/29a1cc56-12fc-4ba4-8bc9-fbbe1492fff0)

<br>
<br>

## 3. 실제 비즈니스 로직에 대한 오류와 특정 라이브러리에 대한 구분하지 못함.
`IllegalArgumentException`은 비즈니스로직뿐 아니라 다른 라이브러리에서도 심심치않게 사용되는 로직입니다.
만약 다른 라이브러리의 오류로 해당 예외가 발생했을때 사용자의 실수인 것 처럼 예외처리를 해버린다면, 이는 사용자에게 큰 혼동을 안겨주게 됩니다.
![image](https://github.com/fcstudy-project/FastTime/assets/139187207/95d1a6e0-fc7d-497d-b7b4-985303206bc3)

### Q) Exception Message를 넘겨주면 되는거 아님?
* A1. 사용자에게는 내부 라이브러리의 오류로 발생하는 문제를 굳이 메시지로 자세히 알려주지 않아도 된다고 생각합니다. 굳이 사용자에게 내부 라이브러리를 정보를 알려주거나 또 알 필요도 없기 때문입니다. 

# 해결
여러단계를 거쳐서 해결할 에정입니다.

## 1. Exception 계층화
* 우선 타 라이브러리와 비즈니스 로직의 예외를 구분할 수 있게 RuntimeException을 상속하는 `ApplicationException`을 생성할 예정입니다. 
* 이의 장점은 이제 Application에서 발생하는 예외만 따로 처리를 할 수 있다는 것입니다.
![image](https://github.com/fcstudy-project/FastTime/assets/139187207/be7bc72d-4fbc-4ee8-97b2-81a88cb6154c)

## 2. ApplicationExcpetionAdvice 추상화
내부적으로 ApplicationException을 추상화하기 위해서 기본적으로 HttpStatus, Message를 가지고 갈 예정입니다.
```java
@Getter
public class ApplicationException extends RuntimeException {

    private HttpStatus httpStatus;

    protected ApplicationException(HttpStatus httpStatus, String message) {
        super(message);
        this.httpStatus = httpStatus;
    }
}
```

```java
@Slf4j
@RestControllerAdvice
public class GlobalExceptionRestAdvice {

    @ExceptionHandler
    public ResponseEntity<ResponseDTO<Object>> applicationException(ApplicationException e) {
        return ResponseEntity
            .status(e.getHttpStatus())
            .body(ResponseDTO.res(e.getHttpStatus(), e.getMessage()));
    }

   ...
}
```

# 개발내용
- [x] 예외 계층화를 실시한다.
- [x] GlobalExceptionAdvice를 생성한다.

<br>
<br>

**Comment by JeongUijeong** [comment]
정리를 너무 잘 하셨네요. 좋은 해결 방안인 것 같아요! 그럼 각 도메인에서 쓰이는 여러 예외 처리는 비즈니스 로직 에러를 뜻하는 인 `ApplicationException`을 상속받으면 되겠네요! 😀

너무 좋습니다! 👍🏻👍🏻

**Comment by KwonJuHwan** [comment]
해결책으로 제시 되고 있는 `1. Exception 계층화` `2. ApplicationExcpetionAdvice 추상화` 이 부분은 `3. 실제 비즈니스 로직에 대한 오류와 특정 라이브러리에 대한 구분하지 못함.` 문제만 해결하는 것으로 보이는데, `1. 의도치 않은 ExceptionAdvice` `2. 중복되는 처리` 문제들은 `GlobalExceptionAdvice`으로 처리하신다는 말씀이신가요?
